### ISSUE TITLE
Tiles don't remain square on Homepage

### ISSUE THREAD

**Issue by treyfortmuller** [andrewbanchich/phantom-jekyll-theme#2]
There's an issue with the tiles such that they don't remain square if the hidden text which appears after a mouseover wraps around. 
<img width="1062" alt="screen shot 2018-05-23 at 1 28 27 am" src="https://user-images.githubusercontent.com/5715025/40412628-b9ba2ff0-5e28-11e8-9915-afdd197adfcb.png">

I might get around to submitting a pull request in the coming weeks if I decide to stick with this theme for my project. I appreciate all the hard work jekyll-ifying this!

**Comment by andrewbanchich** [comment]
Should be fixed now. Can you confirm @treyfortmuller ?

**Comment by treyfortmuller** [comment]
Looks great!
