### ISSUE TITLE
Menu works in Jekyll environment, but not as a static site

### ISSUE THREAD

**Issue by treyfortmuller** [andrewbanchich/phantom-jekyll-theme#3]
I'm working with your Jekyll version of the theme for the site for a club I run at school. Everything is looking good when I run jekyll locally, and everything looks good when I host a temporary development build on github pages. But when I copy the contents of _site onto a separate server run by the campus, the menu stops working for some reason.

Here's the development build hosted on github pages: https://uavs-at-berkeley.github.io/uavs_site/

Here's the site, live on the server I hope to be running it on (hopefully it's not getting too much traffic as the menu is broken): https://uav.berkeley.edu/

Note, that I've used this process described above, for a different organization which I am involved in, this site is live on the same server: https://ucjazz.berkeley.edu/

Any ideas why the menu might break on this particular jekyll theme when Jekyll is not running? A funny thing I've noticed is that when I have ```jekyll serve``` running on my local machine, the menu works even on the live site (https://uav.berkeley.edu/). Any help would be deeply appreciated! The repo for the site is here: https://github.com/UAVs-at-Berkeley/uavs_site

**Comment by andrewbanchich** [comment]
Looking at the code it output, the broken site shows this:

```
<!-- Nav -->
  <nav>
    <ul>
      <li><a href="#menu">Menu</a></li>
    </ul>
  </nav>
```
Did you make any edits that would have caused this?

**Comment by treyfortmuller** [comment]
I did not, here's the pertinent source in the template:

https://github.com/andrewbanchich/phantom-jekyll-theme/blob/master/_includes/header.html

**Comment by treyfortmuller** [comment]
I tried hacking together a completely new sidebar nav and none of my javascript ends up working, similar issue to what's happening with the original source code. Please let me know if you have any hunches I could pursue to fix it. I ended up temporarily replacing the sidenav with a very nonresponsive horizontal topnav in the mean time: https://uav.berkeley.edu/

**Comment by andrewbanchich** [comment]
Sorry, I'm not able to look into this without seeing the code that isn't working. If you could make a separate repo with the non-working menu again I can take a look and will reopen this. Until then, not sure how to diagnose the issue.
